name: stat

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os-version: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Artifacts
        run: |
          go env
          GOOS=$(go env GOOS)
          mkdir -p bin
          go vet -v ./...
          go build -o "bin/stat-$GOOS" -v ./...
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: stat
          path: bin
